CFLAGS=-Wall -g

all:
	make ex17
	make ex17break
	make ex17ex
	make ex17exg
clean:
	rm -r ex17
	rm -r ex17.dSYM
	rm -r ex17break
	rm -r ex17break.dSYM
	rm -r ex17ex
	rm -r ex17ex.dSYM
	rm -r ex17exg
	rm -r ex17exg.dSYM
	rm -r db.dat
