#!/usr/bin/env bash
set -e

make

./ex17ex db.dat c 512 100

./ex17ex db.dat s 1 "brian" "brian@email.com"
./ex17ex db.dat s 2 "bryce" "bryce@email.com"
./ex17ex db.dat s 3 "jennie" "jennie@email.com"
./ex17ex db.dat s 4 "brian" "brian2@email.com"
./ex17ex db.dat s 5 "kris" "kris@email.com"

./ex17ex db.dat g 1
./ex17ex db.dat g 2
./ex17ex db.dat g 3
./ex17ex db.dat g 4
./ex17ex db.dat g 5

./ex17ex db.dat l

./ex17ex db.dat f "name" "brian"
./ex17ex db.dat f "email" "bryce@email.com"

./ex17ex db.dat d 5
./ex17ex db.dat d 4
./ex17ex db.dat d 3
./ex17ex db.dat d 2
./ex17ex db.dat d 1

make clean
